index:
    path: /
    controller: App\Controller\TestController::index


cniPage:
    path: /admin/cni.html
    controller : App\Controller\PagesController::getPageCni


pageInsertSalarie:
    path: /clients/salarie.html
    controller: App\Controller\PagesController::getPageInsertCS


pageInsertIndependant:
    path: /clients/independant.html 
    controller: App\Controller\PagesController::getPageIndependant


pageInsertMoral:
    path: /clients/moral.html
    controller: App\Controller\PagesController::getPageMoral

pageInserCompte:
    path: /insert/compte
    controller: App\Controller\PagesController::getPageInsertCompte

Deconnex:
    path: /logout
    controller: App\Controller\PagesController::logout



# all post routes 
loginForm:
    path: /verify
    controller: App\Controller\UserController::handleUser
    methods: POST


insertSalarie:
    path: /insertSalarie
    controller: App\Controller\ClientsController::insertCSalarie
    methods: POST


insertMoral:
    path: /pageInsertMoral
    controller: App\Controller\ClientsController::insertCMoral
    methods: POST


insertIndependant:
    path: /insertIndependant
    controller: App\Controller\ClientsController::insertCIndependant
    methods: POST

verifyCNI:
    path: /verifyMat
    controller: App\Controller\CompteController::verifyMatricule
    methods: POST


insertCompte:
    path: /compte
    controller: App\Controller\CompteController::insertCompte
    methods: POST




#============= all for the admin ===============

getIndexAdministrateur:
    path: /indexAdmin
    controller: App\Controller\AdminController::indexPage
