#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# all get routes

index:
    path: /
    controller: App\Controller\TestController::index


cniPage:
    path: /admin/cni.html
    controller : App\Controller\PagesController::getPageCni


pageInsertSalarie:
    path: /clients/salarie.html
    controller: App\Controller\PagesController::getPageInsertCS

    
pageInsertIndependant:
    path: /clients/independant.html 
    controller: App\Controller\PagesController::getPageIndependant


pageInsertMoral:
    path: /clients/moral.html
    controller: App\Controller\PagesController::getPageMoral

Deconnex:
    path: /logout
    controller: App\Controller\PagesController::logout


# all post routes 
loginForm:
    path: /verify
    controller: App\Controller\UserController::handleUser
    methods: POST


insertSalarie:
    path: /insertSalarie
    controller: App\Controller\ClientsController::insertCSalarie
    methods: POST


